from __future__ import annotations

from pathlib import Path

import pandas as pd
from pptx import Presentation
from pptx.dml.color import RGBColor
from pptx.enum.text import MSO_ANCHOR
from pptx.util import Inches, Pt

INK = RGBColor(25, 43, 39)
GREEN = RGBColor(26, 116, 91)
MINT = RGBColor(222, 242, 232)
PAPER = RGBColor(248, 250, 248)
MUTED = RGBColor(94, 111, 105)


def _textbox(slide, x, y, w, h, text, size, color=INK, bold=False):
    box = slide.shapes.add_textbox(Inches(x), Inches(y), Inches(w), Inches(h))
    frame = box.text_frame
    frame.clear()
    frame.vertical_anchor = MSO_ANCHOR.MIDDLE
    paragraph = frame.paragraphs[0]
    paragraph.text = str(text)
    paragraph.font.name = "Aptos"
    paragraph.font.size = Pt(size)
    paragraph.font.bold = bold
    paragraph.font.color.rgb = color
    return box


def _base_slide(deck: Presentation):
    slide = deck.slides.add_slide(deck.slide_layouts[6])
    background = slide.background.fill
    background.solid()
    background.fore_color.rgb = PAPER
    return slide


def write_executive_deck(
    summary: dict, drift: pd.DataFrame, model_comparison: pd.DataFrame, path: Path
) -> None:
    deck = Presentation()
    deck.slide_width = Inches(13.333)
    deck.slide_height = Inches(7.5)

    slide = _base_slide(deck)
    accent = slide.shapes.add_shape(1, Inches(0), Inches(0), Inches(0.22), Inches(7.5))
    accent.fill.solid()
    accent.fill.fore_color.rgb = GREEN
    accent.line.fill.background()
    _textbox(slide, 0.8, 0.8, 5.0, 0.45, "ADRYN  /  DATA TRUST INTELLIGENCE", 14, GREEN, True)
    _textbox(slide, 0.8, 1.75, 10.9, 1.0, "Trust signals, made actionable.", 34, INK, True)
    _textbox(
        slide,
        0.8,
        2.9,
        10.5,
        0.7,
        "Executive readout from a reproducible synthetic enterprise run",
        19,
        MUTED,
    )
    _textbox(slide, 0.8, 5.85, 5.8, 0.55, f"RUN  {summary['run_id']}", 12, MUTED)
    _textbox(
        slide, 0.8, 6.35, 6.4, 0.45, f"Seed {summary['seed']}  |  Generated by ADRYN", 11, MUTED
    )

    slide = _base_slide(deck)
    _textbox(slide, 0.7, 0.45, 10.5, 0.6, "Operational signals in this run", 26, INK, True)
    metrics = [
        ("QUALITY FINDINGS", summary["quality_findings"]),
        ("PRIVACY SIGNALS", summary["pii_findings"]),
        ("CONTRACT REVIEWS", summary["contract_records_requiring_review"]),
        ("AI REVIEWS SCORED", summary["ai_reviews_scored"]),
        ("ORDERS FLAGGED", summary["anomalous_orders"]),
        ("EVIDENCE LINKS", summary["evidence_edges"]),
    ]
    for idx, (label, value) in enumerate(metrics):
        col, row = idx % 3, idx // 3
        x, y = 0.7 + col * 4.15, 1.65 + row * 2.2
        tile = slide.shapes.add_shape(1, Inches(x), Inches(y), Inches(3.7), Inches(1.55))
        tile.fill.solid()
        tile.fill.fore_color.rgb = MINT if col == 1 else RGBColor(255, 255, 255)
        tile.line.color.rgb = RGBColor(226, 234, 230)
        _textbox(slide, x + 0.22, y + 0.18, 3.2, 0.36, label, 10, MUTED, True)
        _textbox(slide, x + 0.22, y + 0.58, 3.1, 0.7, f"{value:,}", 28, GREEN, True)
    _textbox(
        slide,
        0.75,
        6.45,
        11.8,
        0.35,
        "Synthetic data; counts are generated from this run and are not production claims.",
        11,
        MUTED,
    )

    slide = _base_slide(deck)
    _textbox(slide, 0.7, 0.45, 11.7, 0.6, "Evaluation and change signals", 26, INK, True)
    _textbox(slide, 0.8, 1.45, 5.6, 0.45, "AI REVIEW RISK MODEL", 12, GREEN, True)
    _textbox(
        slide, 0.8, 2.05, 5.5, 0.55, f"Accuracy  {summary['ai_eval_accuracy']:.3f}", 21, INK, True
    )
    _textbox(
        slide,
        0.8,
        2.7,
        5.5,
        1.4,
        f"Precision  {summary['ai_eval_precision']:.3f}\nRecall  {summary['ai_eval_recall']:.3f}\nROC AUC  {summary['ai_eval_roc_auc']:.3f}",
        16,
        MUTED,
    )
    _textbox(slide, 6.8, 1.45, 5.6, 0.45, "TEMPORAL ORDER AMOUNT CHECK", 12, GREEN, True)
    if not drift.empty and "status" in drift and drift.iloc[0]["status"] != "insufficient_data":
        drift_row = drift.iloc[0]
        drift_text = (
            f"Result  {drift_row['status']}\n"
            f"KS statistic  {drift_row['ks_statistic']:.3f}\n"
            f"p-value  {drift_row['p_value']:.4f}\n"
            f"Effect size  {drift_row['standardized_effect']:.3f}"
        )
    else:
        drift_text = "Insufficient data to compare time periods."
    _textbox(slide, 6.8, 2.05, 5.6, 1.8, drift_text, 16, INK)
    if not model_comparison.empty:
        highest = model_comparison.sort_values("disagreement_rate").iloc[-1]
        _textbox(
            slide,
            0.8,
            4.35,
            11.5,
            0.65,
            f"Highest observed model-group rate: {highest['model_name']}  ·  "
            f"{highest['disagreement_rate']:.1%} across {int(highest['reviews'])} reviews",
            15,
            GREEN,
            True,
        )
    _textbox(
        slide,
        0.8,
        5.8,
        11.6,
        0.55,
        "Model comparison and time checks are exploratory signals; neither establishes causation.",
        12,
        MUTED,
    )

    slide = _base_slide(deck)
    _textbox(slide, 0.7, 0.45, 11.7, 0.6, "Where to focus review capacity", 26, INK, True)
    bullets = [
        f"{summary['privacy_records_requiring_review']:,} customer records are restricted or have unknown consent.",
        f"{summary['contract_records_requiring_review']:,} contract records have a status or value mismatch.",
        f"{summary['ambiguous_ai_reviews']:,} AI reviews fall near the risk decision boundary.",
        "Use the reviewer workspace to filter, inspect evidence, and export the selected queue.",
    ]
    for idx, line in enumerate(bullets):
        _textbox(slide, 0.95, 1.5 + idx * 0.88, 11.2, 0.55, f"{idx + 1:02d}    {line}", 17, INK)
    _textbox(
        slide,
        0.85,
        6.1,
        11.4,
        0.4,
        "Prioritization supports human review; it does not make compliance or customer-impact decisions.",
        11,
        MUTED,
    )
    deck.save(path)
